Feature: Unsuccessful Protection Operations For Various Combinations of User, Operation, Data Element and Single Input Data
    As a user of the Application Protector Java SDK
    I want to verify protection operations fail for invalid, unauthorized and other negative cases
    So that I can ensure errors are handled correctly and data security is not compromised

    Background:
        Given the Application Protector Java SDK is initialized
        And the environment variables DEV_EDITION_EMAIL, DEV_EDITION_PASSWORD and DEV_EDITION_API_KEY are set
        And a policy is deployed with required data elements, users and permissions required to test the scenario

    @tokenization @bulk @string @negative @PDE-96
    Scenario Outline: Validate error message on input data access (list of strings) with user having no appropriate permisions
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user           | data_element | input_data                                                                                                      | result    | output                                                                        | error_message                                                                             |
            | protect   | finance        | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | marketing      | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | hr             | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | robin.goodwill | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | finance        | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | hr             | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | merlin.ishida  | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | finance        | postcode     | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | hr             | postcode     | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | marketing      | postcode     | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | paloma.torres  | city         | Springfield, Shelbyville, Capital City, Smalltown                                                     | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | admin          | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                          | None      | John Doe, Jane Smith, Alice Johnson, Bob Lee                        | None                                                                                      |
            | unprotect | admin          | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | None      | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004 | None                                                                                      |
            | unprotect | admin          | postcode     | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                                                  | None      | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                | None                                                                                      |
            | unprotect | devops         | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                          | None      | John Doe, Jane Smith, Alice Johnson, Bob Lee                        | None                                                                                      |
            | unprotect | devops         | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | None      | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004 | None                                                                                      |
            | unprotect | devops         | postcode     | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                                                  | None      | SW1A 1AA, W1A 0AX, EC1A 1BB, GIR 0AA                                | None                                                                                      |
            | unprotect | jay.banerjee   | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                          | None      | John Doe, Jane Smith, Alice Johnson, Bob Lee                        | None                                                                                      |
            | unprotect | paloma.torres  | datetime     | 2023-09-04T14:30:00, 2022-08-05T10:15:00, 0600-01-01 00:00:00 000, 1970-04-02 07:00:58 369000         | None      | null, null, null, null                                                      | None                                                                                      |
            | unprotect | paloma.torres  | nin          | QQ123456C, CD654321E, EF112233A, GH445566B                                                            | None      | null, null, null, null                                                      | None                                                                                      |
            | unprotect | merlin.ishida  | address      | 123 Main St, Springfield, 456 Elm St, Shelbyville, 789 Oak Ave, Capital City, 101 Maple Rd, Smalltown | None      | null, null, null, null, null, null, null, null                                                      | None                                                                                      |
            | unprotect | merlin.ishida  | ccn          | 4111111122223333, 5500000000000004, 340000000000009, 30000000000004                                   | None      | null, null, null, null                                                      | None                                                                                      |
            | unprotect | admin          | ssn          | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                                    | None      | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                  | None                                                                                      |
            | unprotect | devops         | int          | 12335, 67890, 23456, 78901                                                                            | None      | 12335, 67890, 23456, 78901                                          | None                                                                                      |
            | unprotect | jay.banerjee   | ssn          | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                                    | None      | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                  | None                                                                                      |
            | unprotect | paloma.torres  | ssn          | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                                    | None      | null, null, null, null                                                      | None                                                                                      |
            | unprotect | merlin.ishida  | ssn          | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                                    | None      | null, null, null, null                                                      | None                                                                                      |
            | unprotect | admin          | passport     | X1234567, Y7654321, A1122334, B4455667                                                                | None      | X1234567, Y7654321, A1122334, B4455667                              | None                                                                                      |
            | unprotect | devops         | passport     | X1234567, Y7654321, A1122334, B4455667                                                                | None      | X1234567, Y7654321, A1122334, B4455667                              | None                                                                                      |
            | unprotect | jay.banerjee   | passport     | X1234567, Y7654321, A1122334, B4455667                                                                | None      | X1234567, Y7654321, A1122334, B4455667                              | None                                                                                      |
            | unprotect | paloma.torres  | passport     | X1234567, Y7654321, A1122334, B4455667                                                                | None      | null, null, null, null                                                      | None                                                                                      |
            | unprotect | merlin.ishida  | passport     | X1234567, Y7654321, A1122334, B4455667                                                                | None      | null, null, null, null                                                      | None                                                                                      |
   
    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with user not present in policy for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output                   | error_message                                                                             |
            | protect   | dummyUser | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser | int          | 12335, 67890, 23456, 78901                         | None      | null, null, null, null | None                                                                                      |
            | reprotect | dummyUser | ssn          | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with user not present in policy for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output                   | error_message                                                                             |
            | protect   | dummyUser | name         | John Doe, Jane Smith, Alice Johnson, Bob Lee       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser | int          | 12335, 67890, 23456, 78901                         | None      | null, null, null, null | None                                                                                      |
            | reprotect | dummyUser | ssn          | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with data element not present in policy for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output | error_message                                         |
            | protect   | superuser | dummyDE      | John Doe, Jane Smith, Alice Johnson, Bob Lee       | exception | None   | 2, The data element could not be found in the policy. |
            | unprotect | superuser | dummyDE      | 12335, 67890, 23456, 78901                         | exception | None   | 2, The data element could not be found in the policy. |
            | reprotect | superuser | dummyDE      | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666 | exception | None   | 2, The data element could not be found in the policy. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with data element not present in policy for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output | error_message                                         |
            | protect   | superuser | dummyDE      | John Doe, Jane Smith, Alice Johnson, Bob Lee       | exception | None   | 2, The data element could not be found in the policy. |
            | unprotect | superuser | dummyDE      | 12335, 67890, 23456, 78901                         | exception | None   | 2, The data element could not be found in the policy. |
            | reprotect | superuser | dummyDE      | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666 | exception | None   | 2, The data element could not be found in the policy. |

    @tokenization @bulk @string @negative @PDE-97
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing invalid list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                                                                                                                                                                                                                                                                                                                               | result    | output                                                                                  | error_message                                   |
            | protect   | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | unprotect | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | protect   | superuser | email        | aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaQ@example.coma, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbQ@example.comb, ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccQ@example.comc, ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ@example.comd | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | protect   | superuser | ccn          | aA1, bB2, cC3, dD4                                                                                                                                                                                                                                                                                                             | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | protect   | superuser | ccn          | 4111111122223333, bB2, 4111111122223333, dD4                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | unprotect | superuser | ccn          | aA1, bB2, cC3, dD4                                                                                                                                                                                                                                                                                                             | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | ccn          | aA1, bB2, cC3, dD4                                                                                                                                                                                                                                                                                                             | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | protect   | superuser | int          | abcdef, ghijkl, mnopqr, stuvwx                                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | unprotect | superuser | int          | abcdef, ghijkl, mnopqr, stuvwx                                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | int          | abcdef, ghijkl, mnopqr, stuvwx                                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | protect   | superuser | datetime     | 1906-12-02 13:11:09 4004453117, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333                                                                                                                                                                                                                      | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | unprotect | superuser | datetime     | 1906-12-02 13:11:09 4004453117, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333                                                                                                                                                                                                                      | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | datetime     | 1906-12-02 13:11:09 4004453117, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333                                                                                                                                                                                                                      | None      | null, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333 | None                                            |
            | protect   | superuser | datetime     | 1906:12:02, 1907:01:03, 1908:02:04, 1909:03:05                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | unprotect | superuser | datetime     | 1906:12:02, 1907:01:03, 1908:02:04, 1909:03:05                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | datetime     | 1906:12:02, 1907/01/03, 1908:02:04, 1909-03-05                                                                                                                                                                                                                                                                                 | None      | null, 1907/01/03, null, 1909-03-05                                                | None                                            |
            | protect   | superuser | datetime     | 12/02/1999, 13/03/2000, 14/04/2001, 15/05/2002                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | unprotect | superuser | datetime     | 12/02/1999, 13/03/2000, 14/04/2001, 15/05/2002                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
            | reprotect | superuser | datetime     | 12/02/1999, 13/03/2000, 14/04/2001, 15/05/2002                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. |
    @tokenization @bulk @bytes @negative @PDE-97 @PDE-123
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing invalid list of bytes input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of bytes" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                                                                                                                                                                                                                                                                                                                               | result    | output                                                                                     | error_message                                   |
            | protect   | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | unprotect | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | email        | John Doe, Jane Smith, Alice Johnson, Bob Lee                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | protect   | superuser | email        | aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaQ@example.coma, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbQ@example.comb, ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccQ@example.comc, ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ@example.comd | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | protect   | superuser | ccn          | aA1, bB2, cC3, dD4                                                                                                                                                                                                                                                                                                             | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | protect   | superuser | ccn          | 4111111122223333, bB2, 4111111122223333, dD4                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | unprotect | superuser | ccn          | aA1, bB2, cC3, dD4                                                                                                                                                                                                                                                                                                             | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | ccn          | aA1, bB2, cC3, dD4                                                                                                                                                                                                                                                                                                             | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | protect   | superuser | int          | abcdef, ghijkl, mnopqr, stuvwx                                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | unprotect | superuser | int          | abcdef, ghijkl, mnopqr, stuvwx                                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | int          | abcdef, ghijkl, mnopqr, stuvwx                                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | protect   | superuser | datetime     | 1906-12-02 13:11:09 4004453117, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333                                                                                                                                                                                                                      | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | unprotect | superuser | datetime     | 1906-12-02 13:11:09 4004453117, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333                                                                                                                                                                                                                      | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | datetime     | 1906-12-02 13:11:09 4004453117, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333                                                                                                                                                                                                                      | None      | ��e, 1907-01-01 00:00:00 000, 1908-02-02 02:02:02 222, 1909-03-03 03:03:03 333           | None                                            |
            | protect   | superuser | datetime     | 1906:12:02, 1907:01:03, 1908:02:04, 1909:03:05                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | unprotect | superuser | datetime     | 1906:12:02, 1907:01:03, 1908:02:04, 1909:03:05                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | datetime     | 1906:12:02, 1907/01/03, 1908:02:04, 1909-03-05                                                                                                                                                                                                                                                                                 | None      | ��e, 1907/01/03, ��e, 1909-03-05                                                         | None                                            |
            | protect   | superuser | datetime     | 12/02/1999, 13/03/2000, 14/04/2001, 15/05/2002                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | unprotect | superuser | datetime     | 12/02/1999, 13/03/2000, 14/04/2001, 15/05/2002                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
            | reprotect | superuser | datetime     | 12/02/1999, 13/03/2000, 14/04/2001, 15/05/2002                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. |
    @tokenization @bulk @integer @negative @PDE-97
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing invalid list of integers input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of integers" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output | error_message                          |
            | protect   | superuser | int          | 12345, -4147483648, -1, -4147483648                | exception | None   | Invalid integer value: -4147483648 |
            | unprotect | superuser | int          | 4147483648, 4147483648, 4147483648, 0              | exception | None   | Invalid integer value: 4147483648  |
            | reprotect | superuser | int          | 10147483648, 10147483648, 10147483648, 10147483648 | exception | None   | Invalid integer value: 10147483648 |
    @tokenization @bulk @string @negative @PDE-124 @skip
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing list of strings input data of more than valid max length
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                             | result    | output | error_message                                     |
            | protect   | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
    @tokenization @bulk @bytes @negative @PDE-124 @skip
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing list of bytes input data of more than valid max length
        When the user performs "<operation>" operation using "tokenization" method on the "list of bytes" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                             | result    | output | error_message                                     |
            | protect   | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. |
            | protect   | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. |
            | unprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. |
            | reprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. |
    @tokenization @bulk @integer @negative @PDE-122
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing unsupported data type for data element that supports only string data type (list of integers input data)
        When the user performs "<operation>" operation using "tokenization" method on the "list of integers" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                | result    | output | error_message                                                                  |
            | protect   | superuser | address      | 12456, 1234, 1234, 1234 | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
            | unprotect | superuser | address      | 12456, 1234, 1234, 1234 | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
    # | reprotect | superuser | address      | 12456, 1234, 1234, 1234 | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using encryption data element without passing encrypt_to parameter in the API call for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                             | result    | output | error_message                                                                  |
            | protect   | superuser | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
            | unprotect | superuser | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
            | reprotect | superuser | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |

    @encryption @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using data element of type encryption for various negative scenarios with list of strings input data
        When the user performs "<operation>" operation using "encryption" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user          | data_element | input_data                                                                       | result    | output                   | error_message                                                                             |
            | protect   | finance       | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee                           | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | finance       | text         | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                     | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | jay.banerjee  | text         | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                     | None      | None, null, null, null | None                                                                                      |
            | unprotect | paloma.torres | text         | 2023-09-04, 2023-09-04, 2023-09-04, 2023-09-04                         | None      | None, null, null, null | None                                                                                      |
            | protect   | dummyUser     | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee                           | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser     | text         | SGVsbG8sIEpvIQ==, SGVsbG8sIEpvIQ==, SGVsbG8sIEpvIQ==, SGVsbG8sIEpvIQ== | None      | None, null, null, null | None                                                                                      |
            | reprotect | dummyUser     | text         | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                     | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @encryption @bulk @bytes @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using data element of type encryption for various negative scenarios with list of bytes input data
        When the user performs "<operation>" operation using "encryption" method on the "list of bytes" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user          | data_element | input_data                                                                                   | result    | output                   | error_message                                                                             |
            | protect   | finance       | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | finance       | text         | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | jay.banerjee  | text         | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                 | None      | null, null, null, null | None                                                                                      |
            | unprotect | paloma.torres | text         | 2023-09-04T14:30:00, 2023-09-05T14:30:00, 2023-09-06T14:30:00, 2023-09-07T14:30:00 | None      | null, null, null, null | None                                                                                      |
            | protect   | dummyUser     | text         | John Doe, Jane Smith, Alice Johnson, Bob Lee                                       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser     | text         | 12345, 67890, 23456, 78901                                                         | None      | null, null, null, null | None                                                                                      |
            | reprotect | dummyUser     | text         | 123-45-6789, 987-65-4321, 111-22-3333, 444-55-6666                                 | exception | null                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @encryption @bulk @integer @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using data element of type encryption for various negative scenarios with list of integers input data
        When the user performs "<operation>" operation using "encryption" method on the "list of integers" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user          | data_element | input_data                       | result    | output                   | error_message                                                                             |
            | protect   | finance       | text         | 1234, 1234, 1234, 1234 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | jay.banerjee  | text         | 1234, 1234, 1234, 1234 | None      | None, null, null, null | None                                                                                      |
            | unprotect | paloma.torres | text         | 1234, 1234, 1234, 1234 | None      | None, null, null, null | None                                                                                      |
            | protect   | dummyUser     | text         | 1234, 1234, 1234, 1234 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser     | text         | 1234, 1234, 1234, 1234 | None      | None, null, null, null | None                                                                                      |
            | reprotect | dummyUser     | text         | 1234, 1234, 1234, 1234 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |